Project 2/force-app/main/default/objects/Account/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <summarizedField>AccountQuiz__c.Score__c</summarizedField>
    <summaryForeignKey>AccountQuiz__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Project 2/force-app/main/default/objects/Account/fields/ranking__c.field-meta.xml
<CustomField>
    <fullName>ranking__c</fullName>
    <label>ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project 2/force-app/main/default/classes/indiLeadController.cls
public with sharing class indiLeadController {

    public indiLeadController(){
        
    }



public static list<account> getAccount(){
    list<account> accList =[SELECT name, points__c FROM account ORDER BY points__c DESC LIMIT 5];
    list<account> newaccList = new list<account>();
    for(account a :accList){
        a.ranking__c=accList.indexOf(a)+1;
        newaccList.add(a);
    }
    
    return newaccList;
}

public static list<account> getmyAccount(){
    list<account> myaccList = [SELECT name, points__c FROM account ORDER BY points__c DESC];
    list<account> myownaccList =[SELECT name, points__c FROM account WHERE OwnerId = :UserInfo.getUserID()];
    account myacc=[SELECT name, points__c FROM account WHERE OwnerId = :UserInfo.getUserID()][0];
    integer rank = myaccList.IndexOf(myacc)+1;
    system.debug('rank:'+rank);

    list<account> mynewaccList = new list<account>();
    for(account a : myownaccList){
        a.ranking__c=rank;
        mynewaccList.add(a);
    }

    return mynewaccList;
}

}