Project 2/Project 2/metadataPackage_1568135524403/objects/Questions__c.object
<CustomObject>
    <label>Questions</label>
    <nameField>
        <label>Questions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Quiz__c</fullName>
        <label>Quiz</label>
        <referenceTo>Quiz__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

Project 2/force-app/main/default/objects/Questions__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <label>B</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Project 2/force-app/main/default/objects/Questions__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <label>C</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Project 2/force-app/main/default/objects/Questions__c/fields/CorrectAnswer__c.field-meta.xml
<CustomField>
    <fullName>CorrectAnswer__c</fullName>
    <label>CorrectAnswer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2/force-app/main/default/objects/Questions__c/fields/D__c.field-meta.xml
<CustomField>
    <fullName>D__c</fullName>
    <label>D</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Project 2/Project 2/metadataPackage_1568135524403/objects/Quiz__c.object
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Quizzes</relationshipLabel>
        <relationshipName>Quizzes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Project 2/force-app/main/default/classes/QuizPageController.cls
public class QuizPageController {

      public QuizPageController() {
        q = [SELECT id, Name FROM Quiz__c];
        ques = [SELECT Name ,A__c,B__c,C__c,D__c,CorrectAnswer__c FROM Questions__c WHERE Quiz__c IN :q LIMIT 1 OFFSET 0 ];
        
    }

       public list<quiz__c> q;
       public list<questions__c> ques;


    integer count=0;
    integer limitSize=10;
 
  
 
    public list<Quiz__c> getQuiz() {
        return q;
    }
    
    public list<Questions__c> getQuestions(){
        return ques;
        

    }

    public List<SelectOption> getAnswers() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('A',Ques[0].a__c)); 
        options.add(new SelectOption('B',Ques[0].b__c)); 
        options.add(new SelectOption('C',Ques[0].c__c)); 
        options.add(new SelectOption('D',Ques[0].d__c)); 
        return options; 
    }

    
    public PageReference Q1(){
        count=0;
        return null;
    }

    

    public void submit(){
        
    }



 



}